### ISSUE TITLE
universal_prek loading issue

### ISSUE THREAD

**Issue by SPTKL** [NYCPlanning/db-data-recipes#15]
for some reason universal prek is giving us errors in the following: 
```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/dataflows/base/schema_validator.py", line 49, in schema_validator
    row[f.name] = f.cast_value(row.get(f.name))
  File "/opt/conda/lib/python3.7/site-packages/tableschema/field.py", line 87, in cast_value
    ).format(field=self, value=value))
tableschema.exceptions.CastError: Field "bin" can't cast value "None" for type "integer" with format "default"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/db-data-recipes/pipelines/db-facilities/build.py", line 63, in <module>
    ETL()
  File "/root/db-data-recipes/pipelines/db-facilities/build.py", line 59, in ETL
    dump_2_s3(params=dict(base_path=base_path))
  File "/opt/conda/lib/python3.7/site-packages/dataflows/base/flow.py", line 15, in process
    return self._chain().process()
  File "/opt/conda/lib/python3.7/site-packages/dataflows/base/datastream_processor.py", line 86, in process
    collections.deque(res, maxlen=0)
  File "/opt/conda/lib/python3.7/site-packages/dataflows/processors/dumpers/dumper_base.py", line 69, in row_counter
    for row in iterator:
  File "/opt/conda/lib/python3.7/site-packages/dataflows/processors/dumpers/file_dumper.py", line 64, in rows_processor
    for row in resource:
  File "/opt/conda/lib/python3.7/site-packages/dataflows/base/schema_validator.py", line 51, in schema_validator
    if not on_error(resource['name'], row, i, e):
  File "/opt/conda/lib/python3.7/site-packages/dataflows/base/schema_validator.py", line 22, in raise_exception
    raise ValidationError(res_name, row, i, e)
dataflows.base.schema_validator.ValidationError: 
ROW: {'loccode': 'QAGP', 'prek_type': 'NYCEEC', 'borough': 'Q', 'locname': 'St. Sebastian School', 'note': 'None', 'phone': '718-928-5997', 'address': '39 - 76 58 St', 'postcode': 11377, 'day_length': 1, 'seats': 58, 'x': 1010185, 'y': 211092, 'email': 'admin@stsebastianschool.org', 'website': 'None', 'meals': 5, 'indoor_outdoor': 9, 'extended_day': 3, 'sems_code': '30QAGP', 'latitude': Decimal('40.747453'), 'longitude': Decimal('-73.905545'), 'community_board': 2, 'council_district': 26, 'census_tract': 259, 'bin': 'None', 'bbl': 'None', 'nta': 'Woodside'}
----
```
try force string == True

However since the data source hasn't been confirmed yet, this is low priority

**Comment by SPTKL** [comment]
We have python package compatibility issue, dataflows==0.55 was throwing errors
options: 

- roll back to 0.52
- fix data inconsistencies and force string on all columns
